services:
  kanban:
    image: local/kanban-board:latest
    build:
      context: /home/roomhacker/excode
      dockerfile: Dockerfile
    ports: !override
      - "43328:3000"
    volumes: !override
      - /home/roomhacker/todo-kanban/work-tasks:/app/data/tasks
    environment:
      TASKS_DIR: /app/data/tasks
      NODE_ENV: production
